property_type = {
    "appartment": "appartment",
    "house": "house",
    "garage": "garage",
    "commercial": "commercial",
    "cottage": "cottage",
    "land": "land",
    "storage": "storage",
    "garden": "garden",
    "other": "other",
    "office": "office",
    "sklad": "storage",
    None: "neuvedené"
}

stav = {'pôvodný': 'pôvodný',
        'rekonštrukcia': 'po rekonštrukcii',
        'novostavba': 'novostavba',
        'zateplený': 'zateplený',
        'Vo výstavbe': 'vo výstavbe',
        'Developerský projekt': 'developerský projekt',
        'kompletná rekonštrukcia': 'kompletná rekonštrukcia',
        'čiastočná rekonštrukcia': 'čiastočná rekonštrukcia',
        'pôvodný stav': 'pôvodný',
        'nadstavba': 'nadstavba',
        'výstavba podkrovia': 'výstavba podkrovia',
        'Novostavba': 'novostavba',
        'vo výstavbe': 'vo výstavbe',
        'Pôvodný stav': 'pôvodný',
        'Kompletná rekonštrukcia': 'kompletná rekonštrukcia',
        'Čiastočná rekonštrukcia': 'čiastočná rekonštrukcia',
        'po rekonštrukcii': 'po rekonštrukcii',
        'Rezervované': 'rezervované',
        'po kompletnej rekonštrukcií': 'kompletná rekonštrukcia',
        'úplne prerobený': 'kompletná rekonštrukcia',
        'čiastočne prerobený': 'čiastočná rekonštrukcia',
        'holopriestor': 'holopriestor',
        'nutná rekonštrukcia': 'nutná rekonštrukcia',
        'Rekonšrukcia nutná': 'nutná rekonštrukcia',
        'nedokončený': 'vo výstavbe',
        'Úplna rekonštrukcia': 'kompletná rekonštrukcia',
        'Pôvodný': 'pôvodný',
        'neuvedené': 'neuvedené',
        'Po kompletnej rekonštrukcii': 'kompletná rekonštrukcia',
        'Po čiastočnej rekonštrukcii': 'čiastočná rekonštrukcia',
        'Nový': 'novostavba',
        'Potrebná väčšia rekonštrukcia': 'nutná rekonštrukcia',
        'vstavba podkrovia': 'výstavba podkrovia',
        }
